DROP PROCEDURE adjust_salaries_by_commission;
DROP PACKAGE debug_utils;
DROP TABLE debug_log;

DROP TABLE employees;

CREATE TABLE employees AS
SELECT
    employee_id,
    first_name,
    last_name,
    salary,
    commission_pct
FROM HR.EMPLOYEES;

SELECT *
FROM employees;

-- 1. TABLE USED TO STORE ALL DEBUGGING MESSAGES


CREATE TABLE debug_log
(
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_time TIMESTAMP DEFAULT SYSTIMESTAMP,

    -- Name of the procedure or module that generated the message
    module_name VARCHAR2(100),

    -- Line number in the source code (entered manually)
    line_no NUMBER,

    -- Debug message
    log_message VARCHAR2(4000),

    -- Oracle session ID where the application is running
    session_id VARCHAR2(50)
        DEFAULT SYS_CONTEXT('USERENV', 'SESSIONID')
);


-- 2. DEBUG PACKAGE: debug_utils


CREATE OR REPLACE PACKAGE debug_utils IS

    -- When FALSE, no messages are written into debug_log
    g_debug_mode BOOLEAN := FALSE;

    -- Enable / Disable debugging
    PROCEDURE enable_debug;
    PROCEDURE disable_debug;

    -- Logging procedures
    PROCEDURE log_message(
        p_module_name VARCHAR2,
        p_line_number NUMBER,
        p_message VARCHAR2
    );

    PROCEDURE log_variable(
        p_variable_name VARCHAR2,
        p_variable_value VARCHAR2
    );

    PROCEDURE log_error(
        p_procedure_name VARCHAR2,
        p_error_message VARCHAR2
    );

END debug_utils;
/

CREATE OR REPLACE PACKAGE BODY debug_utils IS

    -- Enable debugging
    PROCEDURE enable_debug IS
    BEGIN
        g_debug_mode := TRUE;
    END;

    -- Disable debugging
    PROCEDURE disable_debug IS
    BEGIN
        g_debug_mode := FALSE;
    END;

    -- Log a standard message
    PROCEDURE log_message(
        p_module_name VARCHAR2,
        p_line_number NUMBER,
        p_message VARCHAR2
    ) IS
    BEGIN
        -- Write only if debugging is enabled
        IF g_debug_mode THEN
            INSERT INTO debug_log
                (module_name, line_no, log_message)
            VALUES
                (p_module_name, p_line_number, p_message);
        END IF;
    END;

    -- Log a variable value
    PROCEDURE log_variable(
        p_variable_name VARCHAR2,
        p_variable_value VARCHAR2
    ) IS
    BEGIN
        IF g_debug_mode THEN
            INSERT INTO debug_log
                (module_name, line_no, log_message)
            VALUES
                (
                    'VARIABLE_LOG',
                    0,
                    'Variable ' || p_variable_name || ' = ' || p_variable_value
                );
        END IF;
    END;

    -- Log an error message
    PROCEDURE log_error(
        p_procedure_name VARCHAR2,
        p_error_message VARCHAR2
    ) IS
    BEGIN
        IF g_debug_mode THEN
            -- line_no = -1 indicates an error
            INSERT INTO debug_log
                (module_name, line_no, log_message)
            VALUES
                (
                    p_procedure_name,
                    -1,
                    'ERROR: ' || p_error_message
                );
        END IF;
    END;

END debug_utils;
/


-- 3. PACKAGE TEST


BEGIN
    debug_utils.enable_debug;

    debug_utils.log_message(
        'TEST_MODULE',
        10,
        'Logging test'
    );

    debug_utils.log_variable(
        'x',
        '123'
    );

    debug_utils.log_error(
        'TEST_PROCEDURE',
        'Invalid value'
    );

    debug_utils.disable_debug;
END;
/

SELECT *
FROM debug_log;


-- 4. PROCEDURE: adjust_salaries_by_commission


CREATE OR REPLACE PROCEDURE adjust_salaries_by_commission IS

    CURSOR employee_cursor IS
        SELECT
            employee_id,
            salary,
            commission_pct
        FROM employees;

    new_salary NUMBER;

BEGIN

    debug_utils.log_message(
        'adjust_salaries_by_commission',
        1,
        'Procedure started'
    );

    FOR employee_record IN employee_cursor LOOP

        debug_utils.log_variable(
            'employee_id',
            TO_CHAR(employee_record.employee_id)
        );

        debug_utils.log_variable(
            'commission_pct',
            CASE
                WHEN employee_record.commission_pct IS NULL THEN 'NULL'
                ELSE TO_CHAR(employee_record.commission_pct)
            END
        );

        IF employee_record.commission_pct IS NOT NULL THEN

            -- Commission available:
            -- increase salary proportionally
            new_salary :=
                employee_record.salary *
                (1 + employee_record.commission_pct);

            debug_utils.log_message(
                'adjust_salaries_by_commission',
                10,
                'Salary increased based on commission percentage'
            );

        ELSE

            -- No commission:
            -- apply a default 2% increase
            new_salary :=
                employee_record.salary * 1.02;

            debug_utils.log_message(
                'adjust_salaries_by_commission',
                11,
                'Salary increased by the default 2%'
            );

        END IF;

        UPDATE employees
        SET salary = new_salary
        WHERE employee_id = employee_record.employee_id;

        debug_utils.log_variable(
            'new_salary',
            TO_CHAR(new_salary)
        );

        debug_utils.log_message(
            'adjust_salaries_by_commission',
            12,
            'Salary successfully updated'
        );

    END LOOP;

    debug_utils.log_message(
        'adjust_salaries_by_commission',
        99,
        'Procedure completed'
    );

EXCEPTION
    WHEN OTHERS THEN

        -- Log the error and re-raise it
        debug_utils.log_error(
            'adjust_salaries_by_commission',
            SQLERRM
        );

        RAISE;

END;
/

-- 5. EXECUTE THE PROCEDURE AND VERIFY THE RESULTS


BEGIN

    debug_utils.enable_debug;

    adjust_salaries_by_commission;

    debug_utils.disable_debug;

END;
/

SELECT *
FROM debug_log
ORDER BY log_time;


-- 6. LOG LEVELS


-- Add a log level column to the existing table
ALTER TABLE debug_log
ADD log_level VARCHAR2(10);

-- Extend the debug package with log levels

CREATE OR REPLACE PACKAGE debug_utils IS

    g_debug_mode BOOLEAN := FALSE;
    g_log_level VARCHAR2(10) := 'DEBUG';

    PROCEDURE enable_debug;
    PROCEDURE disable_debug;

    PROCEDURE log_message(
        p_module_name VARCHAR2,
        p_line_number NUMBER,
        p_message VARCHAR2,
        p_level VARCHAR2 DEFAULT 'INFO'
    );

    PROCEDURE log_variable(
        p_variable_name VARCHAR2,
        p_variable_value VARCHAR2,
        p_level VARCHAR2 DEFAULT 'DEBUG'
    );

    PROCEDURE log_error(
        p_procedure_name VARCHAR2,
        p_error_message VARCHAR2
    );

END debug_utils;
/

CREATE OR REPLACE PACKAGE BODY debug_utils IS

    PROCEDURE enable_debug IS
    BEGIN
        g_debug_mode := TRUE;
    END;

    PROCEDURE disable_debug IS
    BEGIN
        g_debug_mode := FALSE;
    END;

    PROCEDURE log_message(
        p_module_name VARCHAR2,
        p_line_number NUMBER,
        p_message VARCHAR2,
        p_level VARCHAR2
    ) IS
    BEGIN
        IF g_debug_mode THEN
            INSERT INTO debug_log
                (module_name, line_no, log_message, log_level)
            VALUES
                (
                    p_module_name,
                    p_line_number,
                    p_message,
                    p_level
                );
        END IF;
    END;

    PROCEDURE log_variable(
        p_variable_name VARCHAR2,
        p_variable_value VARCHAR2,
        p_level VARCHAR2
    ) IS
    BEGIN
        IF g_debug_mode THEN
            INSERT INTO debug_log
                (module_name, line_no, log_message, log_level)
            VALUES
                (
                    'VARIABLE_LOG',
                    0,
                    'Variable ' || p_variable_name || ' = ' || p_variable_value,
                    p_level
                );
        END IF;
    END;

    PROCEDURE log_error(
        p_procedure_name VARCHAR2,
        p_error_message VARCHAR2
    ) IS
    BEGIN
        IF g_debug_mode THEN
            INSERT INTO debug_log
                (module_name, line_no, log_message, log_level)
            VALUES
                (
                    p_procedure_name,
                    -1,
                    'ERROR: ' || p_error_message,
                    'ERROR'
                );
        END IF;
    END;

END debug_utils;
/


-- LOG LEVEL TEST


BEGIN

    debug_utils.enable_debug;

    debug_utils.log_message(
        'adjust_salaries_by_commission',
        1,
        'Procedure started',
        'INFO'
    );

    debug_utils.log_variable(
        'commission_pct',
        '0.15',
        'DEBUG'
    );

    debug_utils.log_message(
        'adjust_salaries_by_commission',
        10,
        'Salary increased based on commission percentage',
        'INFO'
    );

    debug_utils.log_error(
        'TEST_PROCEDURE',
        'Test error'
    );

    debug_utils.disable_debug;

END;
/

SELECT *
FROM debug_log
ORDER BY log_time;